apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: ns-crawler-1
  labels:
    namespace-crawler-responsibility: master
    namespace-crawler-responsible-for: ns-crawler-2___ns-crawler-3
type: Opaque
data:
  username: Y29kZXJ1c2Vy  
  username1: Y29kZXJ1c2Vy  