apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: ns-crawler-1
  labels:
    namespace-crawler-responsibility: master
    namespace-crawler-responsible-for: ns-crawler-2__ns-crawler-3
type: Opaque
data:
  username: Y29kZXJ1c2Vy  
  username1: Y29kZXJ1c2Vy  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
  namespace: ns-crawler-1
  labels:
    namespace-crawler-responsibility: master
    namespace-crawler-responsible-for: ns-crawler-2__ns-crawler-3
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  