{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "namespace-crawler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "namespace-crawler.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "namespace-crawler.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "namespace-crawler.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "namespace-crawler.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "namespace-crawler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

{{- end }}
